service: basic-serverless-crud

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  timeout: 30
  environment:
    MONGODB_USER: mongodb://localhost:27017

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - offline/**
    - README.md

functions:
  createProduto:
    handler: src/controllers/ProdutoController.postProduto
    events:
      - http:
          path: /produto
          method: post
          cors: true
  getProdutos:
    handler: src/controllers/ProdutoController.getProdutos
    events:
      - http:
          path: /produto
          method: get
          cors: true
  deleteProduto:
    handler: src/controllers/ProdutoController.deleteProduto
    events:
      - http:
          path: /produto
          method: delete
          cors: true
  putProduto:
    handler: src/controllers/ProdutoController.putProduto
    events:
      - http:
          path: /produto
          method: put
          cors: true
